services:
  api:
    build:
      context: ./insta-clone-api
      dockerfile: Dockerfile
    container_name: jeligramy-app-api
    ports:
      - '8000:8000'
    env_file:
      - ./insta-clone-api/.env
    volumes:
      - ./insta-clone-api:/app
    restart: unless-stopped

  front:
    build:
      context: ./insta-clone-front
      dockerfile: Dockerfile
    container_name: jeligramy-app-front
    ports:
      - '3000:3000'
    env_file:
      - ./insta-clone-front/.env
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./insta-clone-front:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
